apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ngx-blog.fullname" . }}-secret
  labels:
    {{- include "ngx-blog.labels" . | nindent 4 }}
type: Opaque
stringData:
  databaseUrl: {{ .Values.secrets.databaseUrl | quote }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
