import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Default settings for NGX Blog CMS
 * WordPress-style configuration stored in database
 */
const defaultSettings = [
  // General Settings (WordPress-compatible names)
  {
    key: 'blogname',
    value: 'My Blog',
    label: 'Site Title',
    description: 'The name of your blog (WordPress: blogname)',
    type: 'text',
    category: 'general',
    autoload: true,
  },
  {
    key: 'blogdescription',
    value: 'A blog powered by NGX Blog CMS',
    label: 'Tagline',
    description: 'Brief description of your site (WordPress: blogdescription)',
    type: 'text',
    category: 'general',
    autoload: true,
  },
  {
    key: 'siteurl',
    value: 'http://localhost:4000',
    label: 'Site URL',
    description: 'The full URL of your site - no trailing slash (WordPress: siteurl)',
    type: 'url',
    category: 'general',
    autoload: true,
  },
  {
    key: 'home',
    value: 'http://localhost:4000',
    label: 'Home URL',
    description: 'The home URL of your site (WordPress: home)',
    type: 'url',
    category: 'general',
    autoload: true,
  },
  {
    key: 'admin_email',
    value: 'admin@example.com',
    label: 'Admin Email',
    description: 'Email address for admin notifications',
    type: 'email',
    category: 'general',
    autoload: true,
  },
  {
    key: 'WPLANG',
    value: 'en',
    label: 'Site Language',
    description: 'Language code, e.g. en, es, fr (WordPress: WPLANG)',
    type: 'text',
    category: 'general',
    autoload: true,
  },
  {
    key: 'timezone_string',
    value: 'UTC',
    label: 'Timezone',
    description: 'Server timezone (WordPress: timezone_string)',
    type: 'text',
    category: 'general',
    autoload: true,
  },
  // Reading Settings (WordPress-compatible)
  {
    key: 'posts_per_page',
    value: '10',
    label: 'Blog pages show at most',
    description: 'Number of posts to show per page (WordPress: posts_per_page)',
    type: 'number',
    category: 'reading',
    autoload: true,
  },
  {
    key: 'show_on_front',
    value: 'posts',
    label: 'Your homepage displays',
    description: 'What to show on the front page: posts or page (WordPress: show_on_front)',
    type: 'text',
    category: 'reading',
    autoload: true,
  },
  {
    key: 'posts_per_rss',
    value: '20',
    label: 'Syndication feeds show the most recent',
    description: 'Number of posts in RSS feed (WordPress: posts_per_rss)',
    type: 'number',
    category: 'reading',
    autoload: true,
  },
  {
    key: 'excerpt_length',
    value: '160',
    label: 'Excerpt Length',
    description: 'Default excerpt length in characters',
    type: 'number',
    category: 'reading',
    autoload: true,
  },

  // Discussion Settings (WordPress-compatible)
  {
    key: 'default_comment_status',
    value: 'open',
    label: 'Default article settings',
    description: 'Allow people to submit comments on new posts (WordPress: default_comment_status)',
    type: 'text',
    category: 'discussion',
    autoload: true,
  },
  {
    key: 'comment_moderation',
    value: '1',
    label: 'Before a comment appears',
    description: 'Comment must be manually approved (WordPress: comment_moderation)',
    type: 'boolean',
    category: 'discussion',
    autoload: true,
  },
  {
    key: 'comment_registration',
    value: '0',
    label: 'Comment author must be registered',
    description: 'Users must be registered and logged in to comment (WordPress: comment_registration)',
    type: 'boolean',
    category: 'discussion',
    autoload: true,
  },
  {
    key: 'close_comments_for_old_posts',
    value: '0',
    label: 'Automatically close comments',
    description: 'Close comments on articles older than X days (WordPress: close_comments_for_old_posts)',
    type: 'boolean',
    category: 'discussion',
    autoload: true,
  },
  {
    key: 'close_comments_days_old',
    value: '14',
    label: 'Days to close comments',
    description: 'Days after which comments are closed (WordPress: close_comments_days_old)',
    type: 'number',
    category: 'discussion',
    autoload: true,
  },
  {
    key: 'thread_comments',
    value: '1',
    label: 'Enable threaded comments',
    description: 'Enable threaded (nested) comments (WordPress: thread_comments)',
    type: 'boolean',
    category: 'discussion',
    autoload: true,
  },
  {
    key: 'thread_comments_depth',
    value: '5',
    label: 'Thread depth',
    description: 'Maximum comment nesting depth (WordPress: thread_comments_depth)',
    type: 'number',
    category: 'discussion',
    autoload: true,
  },

  // SEO Settings
  {
    key: 'seo_meta_description',
    value: 'A blog powered by NGX Blog CMS',
    label: 'Default Meta Description',
    description: 'Default meta description for pages',
    type: 'text',
    category: 'seo',
    autoload: true,
  },
  {
    key: 'seo_meta_keywords',
    value: 'blog, cms, angular',
    label: 'Default Meta Keywords',
    description: 'Comma-separated keywords',
    type: 'text',
    category: 'seo',
    autoload: true,
  },
  {
    key: 'seo_og_type',
    value: 'website',
    label: 'Open Graph Type',
    description: 'Default Open Graph type',
    type: 'text',
    category: 'seo',
    autoload: true,
  },
  {
    key: 'seo_twitter_card',
    value: 'summary_large_image',
    label: 'Twitter Card Type',
    description: 'Default Twitter Card type',
    type: 'text',
    category: 'seo',
    autoload: true,
  },
  {
    key: 'seo_twitter_site',
    value: '',
    label: 'Twitter Site Handle',
    description: 'Twitter username (e.g., @yourblog)',
    type: 'text',
    category: 'seo',
    autoload: true,
  },
  {
    key: 'sitemap_enabled',
    value: 'true',
    label: 'Enable Sitemap',
    description: 'Generate XML sitemap',
    type: 'boolean',
    category: 'seo',
    autoload: true,
  },
  {
    key: 'rss_enabled',
    value: 'true',
    label: 'Enable RSS',
    description: 'Generate RSS feed',
    type: 'boolean',
    category: 'seo',
    autoload: true,
  },

  // Appearance Settings (WordPress-compatible)
  {
    key: 'template',
    value: 'modern-light',
    label: 'Active Theme',
    description: 'Currently active theme (WordPress: template/stylesheet)',
    type: 'text',
    category: 'appearance',
    autoload: true,
  },
  {
    key: 'stylesheet',
    value: 'modern-light',
    label: 'Active Stylesheet',
    description: 'Currently active stylesheet (WordPress: stylesheet)',
    type: 'text',
    category: 'appearance',
    autoload: true,
  },
  {
    key: 'logo_url',
    value: '',
    label: 'Logo URL',
    description: 'URL to your logo image',
    type: 'url',
    category: 'appearance',
    autoload: true,
  },
  {
    key: 'favicon_url',
    value: '',
    label: 'Favicon URL',
    description: 'URL to your favicon',
    type: 'url',
    category: 'appearance',
    autoload: true,
  },
  {
    key: 'header_code',
    value: '',
    label: 'Header Code',
    description: 'Custom HTML/JS for <head> section',
    type: 'text',
    category: 'appearance',
    autoload: false,
  },
  {
    key: 'footer_code',
    value: '',
    label: 'Footer Code',
    description: 'Custom HTML/JS for footer',
    type: 'text',
    category: 'appearance',
    autoload: false,
  },

  // Social Media
  {
    key: 'social_facebook',
    value: '',
    label: 'Facebook URL',
    description: 'Facebook page URL',
    type: 'url',
    category: 'social',
    autoload: true,
  },
  {
    key: 'social_twitter',
    value: '',
    label: 'Twitter URL',
    description: 'Twitter profile URL',
    type: 'url',
    category: 'social',
    autoload: true,
  },
  {
    key: 'social_instagram',
    value: '',
    label: 'Instagram URL',
    description: 'Instagram profile URL',
    type: 'url',
    category: 'social',
    autoload: true,
  },
  {
    key: 'social_linkedin',
    value: '',
    label: 'LinkedIn URL',
    description: 'LinkedIn profile URL',
    type: 'url',
    category: 'social',
    autoload: true,
  },
  {
    key: 'social_github',
    value: '',
    label: 'GitHub URL',
    description: 'GitHub profile URL',
    type: 'url',
    category: 'social',
    autoload: true,
  },
  {
    key: 'social_youtube',
    value: '',
    label: 'YouTube URL',
    description: 'YouTube channel URL',
    type: 'url',
    category: 'social',
    autoload: true,
  },

  // Analytics
  {
    key: 'analytics_google',
    value: '',
    label: 'Google Analytics ID',
    description: 'GA tracking ID (e.g., G-XXXXXXXXXX)',
    type: 'text',
    category: 'analytics',
    autoload: true,
  },
  {
    key: 'analytics_google_gtm',
    value: '',
    label: 'Google Tag Manager ID',
    description: 'GTM container ID (e.g., GTM-XXXXXXX)',
    type: 'text',
    category: 'analytics',
    autoload: true,
  },
  {
    key: 'analytics_facebook_pixel',
    value: '',
    label: 'Facebook Pixel ID',
    description: 'Facebook Pixel tracking ID',
    type: 'text',
    category: 'analytics',
    autoload: true,
  },

  // Email Settings
  {
    key: 'email_from_name',
    value: 'My Blog',
    label: 'From Name',
    description: 'Name used in outgoing emails',
    type: 'text',
    category: 'email',
    autoload: true,
  },
  {
    key: 'email_from_address',
    value: 'noreply@example.com',
    label: 'From Address',
    description: 'Email address used in outgoing emails',
    type: 'email',
    category: 'email',
    autoload: true,
  },

  // Performance
  {
    key: 'cache_enabled',
    value: 'true',
    label: 'Enable Caching',
    description: 'Enable server-side caching',
    type: 'boolean',
    category: 'performance',
    autoload: true,
  },
  {
    key: 'cache_ttl',
    value: '3600',
    label: 'Cache TTL',
    description: 'Cache time-to-live in seconds',
    type: 'number',
    category: 'performance',
    autoload: true,
  },

  // Media
  {
    key: 'media_max_upload_size',
    value: '5',
    label: 'Max Upload Size (MB)',
    description: 'Maximum file upload size in megabytes',
    type: 'number',
    category: 'media',
    autoload: true,
  },
  {
    key: 'media_allowed_types',
    value: 'jpg,jpeg,png,gif,svg,webp,pdf',
    label: 'Allowed File Types',
    description: 'Comma-separated file extensions',
    type: 'text',
    category: 'media',
    autoload: true,
  },
];

export async function seedSettings() {
  console.log('Seeding settings...');

  for (const setting of defaultSettings) {
    await prisma.setting.upsert({
      where: { key: setting.key },
      update: {}, // Don't overwrite existing values
      create: setting,
    });
  }

  console.log(`✅ Seeded ${defaultSettings.length} settings`);
}

export default seedSettings;
